In [ ]:
                                   ASSIGNMENT NO:5

In [ ]:
AIM: To learn about
    1. Logistic Regression 
    2. Differentiate between Linear and Logistic Regression 
    3. Sigmoid Function 
    4. Types of LogisticRegression 
    5. Confusion Matrix Evaluation Metrics 

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv("C:\\Users\\SSOS19\\Desktop\\13215\\archive (9)\\diabetes.csv")

In [11]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [12]:
print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [13]:
df = pd.get_dummies(df, drop_first=True)

In [14]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [15]:
df=df.fillna(df.mean())

In [16]:
cov_matrix = df.cov()
print(cov_matrix)

                          Pregnancies      Glucose  BloodPressure  \
Pregnancies                 11.354056    13.947131       9.214538   
Glucose                     13.947131  1022.248314      94.430956   
BloodPressure                9.214538    94.430956     374.647271   
SkinThickness               -4.390041    29.239183      64.029396   
Insulin                    -28.555231  1220.935799     198.378412   
BMI                          0.469774    55.726987      43.004695   
DiabetesPedigreeFunction    -0.037426     1.454875       0.264638   
Age                         21.570620    99.082805      54.523453   
Outcome                      0.356618     7.115079       0.600697   

                          SkinThickness       Insulin         BMI  \
Pregnancies                   -4.390041    -28.555231    0.469774   
Glucose                       29.239183   1220.935799   55.726987   
BloodPressure                 64.029396    198.378412   43.004695   
SkinThickness                254.

In [18]:
print(df.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [22]:
X = df.drop('Glucose', axis=1)
Y = df['Glucose']

In [23]:
X

Pregnancies  BloodPressure  SkinThickness  Insulin   BMI  \
0              6             72             35        0  33.6   
1              1             66             29        0  26.6   
2              8             64              0        0  23.3   
3              1             66             23       94  28.1   
4              0             40             35      168  43.1   
..           ...            ...            ...      ...   ...   
763           10             76             48      180  32.9   
764            2             70             27        0  36.8   
765            5             72             23      112  26.2   
766            1             60              0        0  30.1   
767            1             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [24]:
Y

0      148
1       85
2      183
3       89
4      137
      ... 
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [27]:
X_train

Pregnancies  BloodPressure  SkinThickness  Insulin   BMI  \
60             2              0              0        0   0.0   
618            9             82             24        0  28.2   
346            1             46             19       83  28.7   
294            0             50              0        0  21.9   
231            6             80             37      370  46.2   
..           ...            ...            ...      ...   ...   
71             5             64             35      140  28.6   
106            1            122              0        0  22.4   
270           10             86             37        0  45.6   
435            0              0              0        0  42.4   
102            0             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  Outcome  
60                      0.304   21        0  
618                     1.282   50        1  
346                     0.654   22        0  
294                     0.254   65        0  
231                     0.238   46        1  
..                        ...  ...      ...  
71                      0.411   26        0  
106                     0.207   27        0  
270                     1.136   38        1  
435                     0.205   29        1  
102                     0.262   21        0  

[614 rows x 8 columns]

In [28]:
X_test

Pregnancies  BloodPressure  SkinThickness  Insulin   BMI  \
668            6             58             33      190  34.0   
324            2             75             32        0  35.7   
624            2             64              0        0  30.8   
690            8             80              0        0  24.6   
473            7             90              0        0  29.9   
..           ...            ...            ...      ...   ...   
355            9             88              0        0  30.4   
534            1             56             30       56  33.3   
344            8             72              0        0  36.8   
296            2             70             38      360  28.0   
462            8             70             40       49  35.3   

     DiabetesPedigreeFunction  Age  Outcome  
668                     0.430   43        0  
324                     0.148   21        0  
624                     0.158   21        0  
690                     0.856   34        0  
473                     0.210   50        0  
..                        ...  ...      ...  
355                     0.302   49        1  
534                     1.251   24        0  
344                     0.485   57        0  
296                     0.337   29        1  
462                     0.705   39        0  

[154 rows x 8 columns]

In [29]:
Y_train 

60      84
618    112
346    139
294    161
231    134
      ... 
71     139
106     96
270    101
435    141
102    125
Name: Glucose, Length: 614, dtype: int64

In [30]:
Y_test

668     98
324    112
624    108
690    107
473    136
      ... 
355    165
534     77
344     95
296    146
462     74
Name: Glucose, Length: 154, dtype: int64

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
X_train

array([[-0.52639686, -3.75268255, -1.32277365, ..., -0.49073479,
        -1.03594038, -0.72881553],
       [ 1.58804586,  0.68034485,  0.23350519, ...,  2.41502991,
         1.48710085,  1.37208932],
       [-0.82846011, -1.2658623 , -0.09071957, ...,  0.54916055,
        -0.94893896, -0.72881553],
       ...,
       [ 1.8901091 ,  0.89659009,  1.07648956, ...,  1.981245  ,
         0.44308379,  1.37208932],
       [-1.13052335, -3.75268255, -1.32277365, ..., -0.78487662,
        -0.33992901,  1.37208932],
       [-1.13052335,  1.43720319, -1.32277365, ..., -0.61552223,
        -1.03594038, -0.72881553]])

In [36]:
X_test

array([[ 0.68185612, -0.61712658,  0.81710976, ..., -0.11637247,
         0.87809089, -0.72881553],
       [-0.52639686,  0.30191569,  0.7522648 , ..., -0.954231  ,
        -1.03594038, -0.72881553],
       [-0.52639686, -0.29275872, -1.32277365, ..., -0.9245197 ,
        -1.03594038, -0.72881553],
       ...,
       [ 1.28598261,  0.13973176, -1.32277365, ...,  0.04703966,
         2.0961108 , -0.72881553],
       [-0.52639686,  0.03160914,  1.14133451, ..., -0.39268751,
        -0.33992901,  1.37208932],
       [ 1.28598261,  0.03160914,  1.27102442, ...,  0.70068816,
         0.53008521, -0.72881553]])

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
logreg = LogisticRegression() 

In [39]:
logreg.fit(X_train, Y_train)

LogisticRegression()

In [43]:
Y_pred_train = logreg.predict(X_train)
Y_pred_test = logreg.predict(X_test)

In [44]:
Y_pred_train

array([ 99, 184,  99, 132, 181,  99, 141, 124, 119,  99, 100, 115,  99,
       117, 114, 163, 114, 128, 125, 153, 165, 128,  99, 154, 125, 128,
       136, 165, 106, 151, 128, 107, 107, 100, 125, 154, 109,  99, 145,
       143, 105,  99, 101,  99, 128, 144, 106, 105, 145, 118, 122, 107,
        99, 105, 144, 136, 100, 117,  99, 146, 112,  99, 165, 130, 117,
       106, 112, 100,  99,  95,  99, 119, 141, 109, 128, 106, 105,  99,
       124, 129, 106, 119, 118, 114, 128, 119,  99,  99, 125,  99,  99,
       117, 165,  99, 114, 100, 144, 111, 125, 124, 140, 120, 114, 146,
       114,  99, 127, 128, 106,  99, 114,  99, 154, 129, 111, 122, 119,
       146, 109, 125, 123, 100,  99, 115, 106, 124, 124, 128, 156, 196,
       125,  90, 125, 145,  99, 123, 111,  76, 171, 100, 128,  99, 117,
       128, 138, 106,  90, 134, 155,  99, 108,  99, 111, 119,  99, 125,
       111, 156, 146,  99, 105,  99, 129, 100,  99, 111, 161, 105, 119,
        99, 125, 114, 129, 100, 165,  99,  95,  99,  99, 124, 10

In [45]:
Y_pred_test

array([100, 111,  99, 130, 125, 120,  99, 119, 126, 132, 125, 105, 124,
       120,  90, 109, 111,  99, 119, 129, 114, 105,  88,  99, 106, 112,
        99, 125, 112, 120, 180, 145, 124, 119, 120, 100, 144, 128, 194,
       141,  99, 137, 120, 164, 125, 173, 176, 111, 120, 165,  99, 136,
       187, 130, 124,  99, 132,  99, 100, 125, 112, 111, 142, 197, 117,
        79,  99, 147, 130, 155, 154, 111, 114, 107,  99, 105, 137, 100,
        95, 117, 125, 109,  99, 105, 100, 129, 151, 128, 111,  99,  99,
       117,  99, 145, 129,  81, 114, 100, 173, 106, 105, 107, 156, 123,
       130, 105, 109, 128, 128, 100,  99, 130,  99, 112, 100,  87, 109,
        99,  99,  99,  99, 100, 112, 118,  99, 144, 109, 168, 138, 126,
       130, 187,  82, 124, 173,  99, 125, 133, 145,  99,  99,  99, 125,
       165, 107, 100, 118,  99, 105, 125, 100, 120, 124, 100], dtype=int64)

In [48]:
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, recall_score
cm = confusion_matrix(Y_test, Y_pred_test)

In [49]:
print("Cofusion Matrix:")
print(cm)

Cofusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [50]:
accuracy = accuracy_score(Y_test, Y_pred_test)
print("accuracy:", accuracy)

accuracy: 0.006493506493506494


In [54]:
precision = precision_score(Y_test, Y_pred_test, average='macro')
print("precision:", precision)

precision: 0.000825082508250825


C:\Users\SSOS19\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
precision = precision_score(Y_test, Y_pred_test, average='weighted')
print("precision:", precision)

precision: 0.0010822510822510823


C:\Users\SSOS19\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [58]:
recall = recall_score(Y_test, Y_pred_test, average='macro')
print("recall:",recall)

recall: 0.0049504950495049506


C:\Users\SSOS19\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
NAME : SURAJ KANADE
ROLL NO: 13215